services:
  ci:
    container_name: ${CI_CONTAINER}
    entrypoint:
      - sleep
      - infinity
    environment:
      - PYTHONUNBUFFERED=1
    image: ${CI_IMAGE_CI}
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
