version: "3.8"
services:
  picopt-build-builder:
    build:
      context: .
      dockerfile: build.Dockerfile
    image: ajslater/picopt-builder
    container_name: picopt-build-builder
  picopt-lint:
    image: ajslater/picopt-builder
    container_name: picopt-lint
    command: make lint
  picopt-test:
    image: ajslater/picopt-builder
    container_name: picopt-test
    volumes:
      - ./test-results:/app/test-results
    command: make test
  picopt-build:
    image: ajslater/picopt-builder
    container_name: picopt-build
    volumes:
      - ./dist:/app/dist
    command: make build
  picopt:
    build:
      context: .
      dockerfile: Dockerfile
    image: ajslater/picopt
    container_name: picopt
