#!/bin/sh
if [ "$(whoami)" != 'root' ]; then
  echo "You have no permission to run $0 as non-root user."
  exit 1
fi

export PATH=$PATH:/opt/local/bin

port selfupdate
port -d sync
portindex
port upgrade outdated
