version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t picopt-builder .
      - run: docker run -ti picopt-builder -v /tmp/test-results:test-results bin/tests.sh
      - store_test_results:
            path: /tmp/test-results

