version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t picopt-builder .
      - run: mkdir -p /test-results
      - run: docker run -ti picopt-builder -v test-results:/test-results bin/tests.sh
      - store_test_results:
            path: /test-results

