version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: apt update
      - run: ./ci/apt.sh
      - run: ./ci/pngout.sh
      - run: ./ci/mozjpeg.sh
      - run: ./setup.py build develop
  test:
    machine: true
    parallelism: 4
    steps:
      - run: nosetests

