jobs:
    build:
        docker:
            - image: cimg/python:3.9
        steps:
            - checkout
            - run: ci/build.sh
            - run: ci/test.sh
            - store_test_results:
                path: test-results
            - store_artifacts:
                path: test-results/coverage
            - persist_to_workspace:
                paths:
                    - ./README.md
                    - ./ci
                    - ./dist
                    - ./pyproject.toml
                root: .
    deploy:
        docker:
            - image: cimg/python:3.9
        steps:
            - attach_workspace:
                at: .
            - run:
                command: pip install poetry
                name: Install poetry
            - run:
                command: ./ci/publish-pypi.sh
                name: Publish Package to PyPi
version: 2.1
workflows:
    main:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - dev
                            - develop
                            - circleci
                            - release
                            - master
                            - /.*-ci/
            - deploy:
                filters:
                    branches:
                        only:
                            - circleci
                            - release
                            - master
            - requires:
                - build
    version: 2.1

