version: 2
jobs:
  build:
      docker:
          image: circleci/python
    branches:
      only: master
    steps:
      - checkout
      - run: ./ci/apt.sh
      - run: ./ci/pngout.sh
      - run: ./ci/mozjpeg.sh
