version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t picopt-builder .
  test:
    docker:
        - image: picopt-builder
    steps:
      - run: nosetests
