version: 2
jobs:
  build:
    docker:
       - image: ubuntu:bionic
    steps:
      - checkout
      - run: apt update
      - run: ./ci/apt.sh
      - run: ./ci/pngout.sh
      - run: ./ci/mozjpeg.sh
      - run: ./setup.py build develop
  test:
    parallelism: 4
    steps:
      - run: nosetests

