#!/bin/sh
export PATH=$PATH:/ffp/bin:/ffp/sbin
HOST=koi
LOCKFILE=/var/lock/backup-${HOST}
SOURCE=/
DEST=/media/esata/${HOST}
RSYNC=${SOURCE}/ffp/bin/rsync
RSYNC_CMD="${RSYNC} -av --no-whole-file --inplace --delete --stats"

exit_unlock()
{
  if [ $1 ]; then
    rm -f $LOCKFILE
    return $1
  fi
}

if [ -f $LOCKFILE ]; then
 echo $LOCKFILE detected.
 echo $0 already running.
 exit 1
fi
touch $LOCKFILE

${HOME}/bin/mount-retry.sh sdc
exit_unlock $?

backup_time_machine()
{
    BU=${1}
    echo Backing up $BU Backups
    ${HOME}/bin/koi/switch-netatalk.sh ${BU}_ro
    exit_unlock $?
    ${RSYNC_CMD} $SOURCE/home/${BU} $DEST/${HOST}/home/${BU}
    exit_unlock $?
}

if [ "$1" != "-n" ]; then
    backup_time_machine aj
    backup_time_machine mandy
    #backup_time_machine bullfrog
    ${HOME}/bin/koi/switch-netatalk.sh ALL
fi

echo Starting sync from $SOURCE to $DEST
${RSYNC_CMD} --include-from="${HOME}/bin/koi/koi-rsync-backup.include' $SOURCE $DEST
rm -f $LOCKFILE
echo Finished.
